# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'yolov8.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1195, 635)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(18)
        Form.setFont(font)
        Form.setStyleSheet("​\n"
"QSlider::handle:horizontal{ /**设置滑块样式**/\n"
"    width:8px;\n"
"    background-color:rgb(255, 253, 252);\n"
"    margin:-11px 0px -11px 0px;\n"
"    border-radius:3px;\n"
"}\n"
"QSlider::groove:horizontal{\n"
"    height:2px;\n"
"    background-color:rgb(29, 70, 179);\n"
"}\n"
"QScrollBar::add-line:vertical { /**设置向下按钮**/\n"
"    background:02123e;\n"
"    border:1px solid #083863;\n"
"}\n"
"QScrollBar::sub-line:vertical { /**设置向上按钮**/\n"
"    background:02123e;\n"
"    border:1px solid #083863;\n"
"}\n"
"QSlider::add-page:horizontal{ /**设置滚动条的增加页区域**/\n"
"    background-color:rgb(29, 70, 179);\n"
"}\n"
"QSlider::sub-page:horizontal{   /**设置滚动条的减少页区域**/\n"
"    background-color:rgb(26,217,110);\n"
"}\n"
"QSlider::groove:horizontal {\n"
"    border: 1px solid #bbb;\n"
"    background-color: #fff;\n"
"    background:#1E3E62;\n"
"    height: 10px;\n"
"    border-radius: 4px;\n"
"}\n"
" \n"
"QSlider::sub-page:horizontal {\n"
"   background: qlineargradient(x1: 0, y1: 0,    x2: 0, y2: 1,\n"
"        stop: 0 #0078d7, stop: 1 #0063ad);\n"
"   /** border: 1px solid #777;**/\n"
"    height: 8px;\n"
"    border-radius: 4px;\n"
"}\n"
" \n"
"QSlider::add-page:horizontal {\n"
"    background: #1E3E62;\n"
"   /** border: 1px solid #777;**/\n"
"    height: 8px;\n"
"    border-radius: 4px;\n"
"}\n"
" \n"
"QSlider::handle:horizontal {\n"
"    /**background: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
"        stop:0 #eee, stop:1 #ccc);\n"
"    border: 1px solid #777;\n"
"    width: 13px;\n"
"    margin-top: -2px;\n"
"    margin-bottom: -2px;\n"
"    border-radius: 4px;**/\n"
"}\n"
"QSlider::handle:horizontal{\n"
"    image: url(:/slices/bkpv (9).png);\n"
"    width:20px;\n"
"    height:20px;\n"
"    margin-top:-2px;\n"
"    margin-bottom:-2px;\n"
"}\n"
"QSlider::handle:horizontal:hover {\n"
"   /** background: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
"        stop:0 #fff, stop:1 #ddd);\n"
"    border: 1px solid #444;\n"
"    border-radius: 4px;**/\n"
"}\n"
"QSlider::sub-page:horizontal:disabled {\n"
"    background: #bbb;\n"
"    border-color: #999;\n"
"}\n"
"QSlider::add-page:horizontal:disabled {\n"
"    background: #eee;\n"
"    border-color: #999;\n"
"}\n"
"QSlider::handle:horizontal:disabled {\n"
"    background: #eee;\n"
"    border: 1px solid #aaa;\n"
"    border-radius: 4px;\n"
"}\n"
" \n"
"QSlider::groove:vertical {\n"
"    border: 1px solid #bbb;\n"
"    background: white;\n"
"    width: 10px;\n"
"    border-radius: 4px;\n"
"}\n"
" \n"
"QSlider::sub-page:vertical {\n"
"    background: qlineargradient(x1: 0, y1: 1, x2: 1, y2: 1,\n"
"        stop: 0 #0078d7, stop: 1 #0063ad);\n"
"    border: 1px solid #777;\n"
"    width: 10px;\n"
"    border-radius: 4px;\n"
"}\n"
" \n"
"QSlider::add-page:vertical {\n"
"    background: #fff;\n"
"    border: 1px solid #777;\n"
"    width: 10px;\n"
"    border-radius: 4px;\n"
"}\n"
" \n"
"QSlider::handle:vertical {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
"        stop:0 #eee, stop:1 #ccc);\n"
"    border: 1px solid #777;\n"
"    height: 13px;\n"
"    margin-left: -2px;\n"
"    margin-right: -2px;\n"
"    border-radius: 4px;\n"
"}\n"
"QSlider::handle:vertical:hover {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
"        stop:0 #fff, stop:1 #ddd);\n"
"    border: 1px solid #444;\n"
"    border-radius: 4px;\n"
"}\n"
"QSlider::sub-page:vertical:disabled {\n"
"    background: #bbb;\n"
"    border-color: #999;\n"
"}\n"
"QSlider::add-page:vertical:disabled {\n"
"    background: #eee;\n"
"    border-color: #999;\n"
"}\n"
"QSlider::handle:vertical:disabled {\n"
"    background: #eee;\n"
"    border: 1px solid #aaa;\n"
"    border-radius: 4px;\n"
"}\n"
" \n"
"QSlider::groove:horizontal:disabled {\n"
"    background: #1E3E62;\n"
"    border-color: #999;\n"
"}")
        self.original_image = QtWidgets.QLabel(Form)
        self.original_image.setGeometry(QtCore.QRect(10, 90, 431, 361))
        self.original_image.setMaximumSize(QtCore.QSize(600, 600))
        self.original_image.setStyleSheet("QLabel {\n"
"    background-color: white;\n"
"    color: white;\n"
"}\n"
"")
        self.original_image.setObjectName("original_image")
        self.detected_image = QtWidgets.QLabel(Form)
        self.detected_image.setGeometry(QtCore.QRect(477, 87, 431, 361))
        self.detected_image.setMaximumSize(QtCore.QSize(600, 600))
        self.detected_image.setStyleSheet("QLabel {\n"
"    background-color: white;\n"
"    color: white;\n"
"}\n"
"")
        self.detected_image.setObjectName("detected_image")
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 490, 901, 61))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.picture_detect_pushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.picture_detect_pushButton.setMaximumSize(QtCore.QSize(16777215, 40))
        self.picture_detect_pushButton.setStyleSheet("QPushButton\n"
"{\n"
"    color:#ffffff; /*文字颜色*/\n"
"    background-color:qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop:0 #aa55ff, stop: 1 #1296db);/*背景色*/\n"
"    border-style:outset; /*边框风格*/\n"
"    border-width:2px;/*边框宽度*/\n"
"    border-color:#0055ff; /*边框颜色*/\n"
"    border-radius:10px; /*边框倒角*/\n"
"    font:bold 14px; /*字体*/\n"
"    font-family: Segoe UI;\n"
"    min-width:100px;/*控件最小宽度*/\n"
"    background-image: url(\"./image.png\");\n"
"    min-height:20px;/*控件最小高度*/\n"
"    padding:4px;/*内边距*/\n"
"}\n"
" \n"
"QPushButton:hover\n"
"{\n"
"    color:#ffffff; /*文字颜色*/\n"
"    background-color:qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop:0 #ff55ff, stop: 1 #1296db);/*背景色*/\n"
"    border-style:outset; /*边框风格*/\n"
"    border-width:2px;/*边框宽度*/\n"
"    border-color:#0055ff; /*边框颜色*/\n"
"    border-radius:10px; /*边框倒角*/\n"
"    font:bold 14px; /*字体*/\n"
"    font-family: Segoe UI;\n"
"    min-width:100px;/*控件最小宽度*/\n"
"    min-height:20px;/*控件最小高度*/\n"
"    padding:4px;/*内边距*/\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    color:#ffffff; /*文字颜色*/\n"
"    background-color:qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop:0 #ff55ff, stop: 1 #aa00ff);/*背景色*/\n"
"    border-style:outset; /*边框风格*/\n"
"    border-width:2px;/*边框宽度*/\n"
"    border-color:#0055ff; /*边框颜色*/\n"
"    border-radius:10px; /*边框倒角*/\n"
"    font:bold 14px; /*字体*/\n"
"    font-family: Segoe UI;\n"
"    min-width:100px;/*控件最小宽度*/\n"
"    min-height:20px;/*控件最小高度*/\n"
"    padding:4px;/*内边距*/\n"
"}")
        self.picture_detect_pushButton.setObjectName("picture_detect_pushButton")
        self.horizontalLayout_2.addWidget(self.picture_detect_pushButton)
        self.stop_detect_pushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.stop_detect_pushButton.setMaximumSize(QtCore.QSize(16777215, 40))
        self.stop_detect_pushButton.setStyleSheet("QPushButton\n"
"{\n"
"    color:#ffffff; /*文字颜色*/\n"
"    background-color:qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop:0 #aa55ff, stop: 1 #1296db);/*背景色*/\n"
"    border-style:outset; /*边框风格*/\n"
"    border-width:2px;/*边框宽度*/\n"
"    border-color:#0055ff; /*边框颜色*/\n"
"    border-radius:10px; /*边框倒角*/\n"
"    font:bold 14px; /*字体*/\n"
"    font-family: Segoe UI;\n"
"    min-width:100px;/*控件最小宽度*/\n"
"    background-image: url(\"./image.png\");\n"
"    min-height:20px;/*控件最小高度*/\n"
"    padding:4px;/*内边距*/\n"
"}\n"
" \n"
"QPushButton:hover\n"
"{\n"
"    color:#ffffff; /*文字颜色*/\n"
"    background-color:qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop:0 #ff55ff, stop: 1 #1296db);/*背景色*/\n"
"    border-style:outset; /*边框风格*/\n"
"    border-width:2px;/*边框宽度*/\n"
"    border-color:#0055ff; /*边框颜色*/\n"
"    border-radius:10px; /*边框倒角*/\n"
"    font:bold 14px; /*字体*/\n"
"    font-family: Segoe UI;\n"
"    min-width:100px;/*控件最小宽度*/\n"
"    min-height:20px;/*控件最小高度*/\n"
"    padding:4px;/*内边距*/\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    color:#ffffff; /*文字颜色*/\n"
"    background-color:qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop:0 #ff55ff, stop: 1 #aa00ff);/*背景色*/\n"
"    border-style:outset; /*边框风格*/\n"
"    border-width:2px;/*边框宽度*/\n"
"    border-color:#0055ff; /*边框颜色*/\n"
"    border-radius:10px; /*边框倒角*/\n"
"    font:bold 14px; /*字体*/\n"
"    font-family: Segoe UI;\n"
"    min-width:100px;/*控件最小宽度*/\n"
"    min-height:20px;/*控件最小高度*/\n"
"    padding:4px;/*内边距*/\n"
"}")
        self.stop_detect_pushButton.setObjectName("stop_detect_pushButton")
        self.horizontalLayout_2.addWidget(self.stop_detect_pushButton)
        self.exit_system_pushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.exit_system_pushButton.setMaximumSize(QtCore.QSize(16777215, 40))
        self.exit_system_pushButton.setStyleSheet("QPushButton\n"
"{\n"
"    color:#ffffff; /*文字颜色*/\n"
"    background-color:qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop:0 #aa55ff, stop: 1 #1296db);/*背景色*/\n"
"    border-style:outset; /*边框风格*/\n"
"    border-width:2px;/*边框宽度*/\n"
"    border-color:#0055ff; /*边框颜色*/\n"
"    border-radius:10px; /*边框倒角*/\n"
"    font:bold 14px; /*字体*/\n"
"    font-family: Segoe UI;\n"
"    min-width:100px;/*控件最小宽度*/\n"
"    background-image: url(\"./image.png\");\n"
"    min-height:20px;/*控件最小高度*/\n"
"    padding:4px;/*内边距*/\n"
"}\n"
" \n"
"QPushButton:hover\n"
"{\n"
"    color:#ffffff; /*文字颜色*/\n"
"    background-color:qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop:0 #ff55ff, stop: 1 #1296db);/*背景色*/\n"
"    border-style:outset; /*边框风格*/\n"
"    border-width:2px;/*边框宽度*/\n"
"    border-color:#0055ff; /*边框颜色*/\n"
"    border-radius:10px; /*边框倒角*/\n"
"    font:bold 14px; /*字体*/\n"
"    font-family: Segoe UI;\n"
"    min-width:100px;/*控件最小宽度*/\n"
"    min-height:20px;/*控件最小高度*/\n"
"    padding:4px;/*内边距*/\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    color:#ffffff; /*文字颜色*/\n"
"    background-color:qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop:0 #ff55ff, stop: 1 #aa00ff);/*背景色*/\n"
"    border-style:outset; /*边框风格*/\n"
"    border-width:2px;/*边框宽度*/\n"
"    border-color:#0055ff; /*边框颜色*/\n"
"    border-radius:10px; /*边框倒角*/\n"
"    font:bold 14px; /*字体*/\n"
"    font-family: Segoe UI;\n"
"    min-width:100px;/*控件最小宽度*/\n"
"    min-height:20px;/*控件最小高度*/\n"
"    padding:4px;/*内边距*/\n"
"}")
        self.exit_system_pushButton.setObjectName("exit_system_pushButton")
        self.horizontalLayout_2.addWidget(self.exit_system_pushButton)
        self.resultTable = QtWidgets.QTableWidget(Form)
        self.resultTable.setGeometry(QtCore.QRect(940, 90, 241, 131))
        self.resultTable.setLineWidth(1)
        self.resultTable.setColumnCount(6)
        self.resultTable.setObjectName("resultTable")
        self.resultTable.setRowCount(0)
        self.result_label = QtWidgets.QLabel(Form)
        self.result_label.setGeometry(QtCore.QRect(880, 40, 311, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(18)
        self.result_label.setFont(font)
        self.result_label.setObjectName("result_label")
        self.input_image_label = QtWidgets.QLabel(Form)
        self.input_image_label.setGeometry(QtCore.QRect(170, 50, 101, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(18)
        self.input_image_label.setFont(font)
        self.input_image_label.setObjectName("input_image_label")
        self.output_image_label = QtWidgets.QLabel(Form)
        self.output_image_label.setGeometry(QtCore.QRect(640, 50, 101, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(18)
        self.output_image_label.setFont(font)
        self.output_image_label.setObjectName("output_image_label")
        self.save_result_pushButton = QtWidgets.QPushButton(Form)
        self.save_result_pushButton.setGeometry(QtCore.QRect(960, 240, 211, 40))
        self.save_result_pushButton.setMaximumSize(QtCore.QSize(16777215, 40))
        self.save_result_pushButton.setStyleSheet("QPushButton\n"
"{\n"
"    color:#ffffff; /*文字颜色*/\n"
"    background-color:qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop:0 #aa55ff, stop: 1 #1296db);/*背景色*/\n"
"    border-style:outset; /*边框风格*/\n"
"    border-width:2px;/*边框宽度*/\n"
"    border-color:#0055ff; /*边框颜色*/\n"
"    border-radius:10px; /*边框倒角*/\n"
"    font:bold 14px; /*字体*/\n"
"    font-family: Segoe UI;\n"
"    min-width:100px;/*控件最小宽度*/\n"
"    background-image: url(\"./image.png\");\n"
"    min-height:20px;/*控件最小高度*/\n"
"    padding:4px;/*内边距*/\n"
"}\n"
" \n"
"QPushButton:hover\n"
"{\n"
"    color:#ffffff; /*文字颜色*/\n"
"    background-color:qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop:0 #ff55ff, stop: 1 #1296db);/*背景色*/\n"
"    border-style:outset; /*边框风格*/\n"
"    border-width:2px;/*边框宽度*/\n"
"    border-color:#0055ff; /*边框颜色*/\n"
"    border-radius:10px; /*边框倒角*/\n"
"    font:bold 14px; /*字体*/\n"
"    font-family: Segoe UI;\n"
"    min-width:100px;/*控件最小宽度*/\n"
"    min-height:20px;/*控件最小高度*/\n"
"    padding:4px;/*内边距*/\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    color:#ffffff; /*文字颜色*/\n"
"    background-color:qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop:0 #ff55ff, stop: 1 #aa00ff);/*背景色*/\n"
"    border-style:outset; /*边框风格*/\n"
"    border-width:2px;/*边框宽度*/\n"
"    border-color:#0055ff; /*边框颜色*/\n"
"    border-radius:10px; /*边框倒角*/\n"
"    font:bold 14px; /*字体*/\n"
"    font-family: Segoe UI;\n"
"    min-width:100px;/*控件最小宽度*/\n"
"    min-height:20px;/*控件最小高度*/\n"
"    padding:4px;/*内边距*/\n"
"}")
        self.save_result_pushButton.setObjectName("save_result_pushButton")
        self.doubt_accuracy_pushButton = QtWidgets.QPushButton(Form)
        self.doubt_accuracy_pushButton.setGeometry(QtCore.QRect(960, 310, 211, 40))
        self.doubt_accuracy_pushButton.setMaximumSize(QtCore.QSize(16777215, 40))
        self.doubt_accuracy_pushButton.setStyleSheet("QPushButton\n"
"{\n"
"    color:#ffffff; /*文字颜色*/\n"
"    background-color:qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop:0 #aa55ff, stop: 1 #1296db);/*背景色*/\n"
"    border-style:outset; /*边框风格*/\n"
"    border-width:2px;/*边框宽度*/\n"
"    border-color:#0055ff; /*边框颜色*/\n"
"    border-radius:10px; /*边框倒角*/\n"
"    font:bold 14px; /*字体*/\n"
"    font-family: Segoe UI;\n"
"    min-width:100px;/*控件最小宽度*/\n"
"    background-image: url(\"./image.png\");\n"
"    min-height:20px;/*控件最小高度*/\n"
"    padding:4px;/*内边距*/\n"
"}\n"
" \n"
"QPushButton:hover\n"
"{\n"
"    color:#ffffff; /*文字颜色*/\n"
"    background-color:qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop:0 #ff55ff, stop: 1 #1296db);/*背景色*/\n"
"    border-style:outset; /*边框风格*/\n"
"    border-width:2px;/*边框宽度*/\n"
"    border-color:#0055ff; /*边框颜色*/\n"
"    border-radius:10px; /*边框倒角*/\n"
"    font:bold 14px; /*字体*/\n"
"    font-family: Segoe UI;\n"
"    min-width:100px;/*控件最小宽度*/\n"
"    min-height:20px;/*控件最小高度*/\n"
"    padding:4px;/*内边距*/\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    color:#ffffff; /*文字颜色*/\n"
"    background-color:qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop:0 #ff55ff, stop: 1 #aa00ff);/*背景色*/\n"
"    border-style:outset; /*边框风格*/\n"
"    border-width:2px;/*边框宽度*/\n"
"    border-color:#0055ff; /*边框颜色*/\n"
"    border-radius:10px; /*边框倒角*/\n"
"    font:bold 14px; /*字体*/\n"
"    font-family: Segoe UI;\n"
"    min-width:100px;/*控件最小宽度*/\n"
"    min-height:20px;/*控件最小高度*/\n"
"    padding:4px;/*内边距*/\n"
"}")
        self.doubt_accuracy_pushButton.setObjectName("doubt_accuracy_pushButton")
        self.model_combobox = QtWidgets.QComboBox(Form)
        self.model_combobox.setGeometry(QtCore.QRect(1050, 390, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.model_combobox.setFont(font)
        self.model_combobox.setObjectName("model_combobox")
        self.output_image_label_2 = QtWidgets.QLabel(Form)
        self.output_image_label_2.setGeometry(QtCore.QRect(950, 390, 101, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(18)
        self.output_image_label_2.setFont(font)
        self.output_image_label_2.setObjectName("output_image_label_2")
        self.refresh_models_button = QtWidgets.QPushButton(Form)
        self.refresh_models_button.setGeometry(QtCore.QRect(960, 440, 211, 40))
        self.refresh_models_button.setMaximumSize(QtCore.QSize(16777215, 40))
        self.refresh_models_button.setStyleSheet("QPushButton\n"
"{\n"
"    color:#ffffff; /*文字颜色*/\n"
"    background-color:qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop:0 #aa55ff, stop: 1 #1296db);/*背景色*/\n"
"    border-style:outset; /*边框风格*/\n"
"    border-width:2px;/*边框宽度*/\n"
"    border-color:#0055ff; /*边框颜色*/\n"
"    border-radius:10px; /*边框倒角*/\n"
"    font:bold 14px; /*字体*/\n"
"    font-family: Segoe UI;\n"
"    min-width:100px;/*控件最小宽度*/\n"
"    background-image: url(\"./image.png\");\n"
"    min-height:20px;/*控件最小高度*/\n"
"    padding:4px;/*内边距*/\n"
"}\n"
" \n"
"QPushButton:hover\n"
"{\n"
"    color:#ffffff; /*文字颜色*/\n"
"    background-color:qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop:0 #ff55ff, stop: 1 #1296db);/*背景色*/\n"
"    border-style:outset; /*边框风格*/\n"
"    border-width:2px;/*边框宽度*/\n"
"    border-color:#0055ff; /*边框颜色*/\n"
"    border-radius:10px; /*边框倒角*/\n"
"    font:bold 14px; /*字体*/\n"
"    font-family: Segoe UI;\n"
"    min-width:100px;/*控件最小宽度*/\n"
"    min-height:20px;/*控件最小高度*/\n"
"    padding:4px;/*内边距*/\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    color:#ffffff; /*文字颜色*/\n"
"    background-color:qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop:0 #ff55ff, stop: 1 #aa00ff);/*背景色*/\n"
"    border-style:outset; /*边框风格*/\n"
"    border-width:2px;/*边框宽度*/\n"
"    border-color:#0055ff; /*边框颜色*/\n"
"    border-radius:10px; /*边框倒角*/\n"
"    font:bold 14px; /*字体*/\n"
"    font-family: Segoe UI;\n"
"    min-width:100px;/*控件最小宽度*/\n"
"    min-height:20px;/*控件最小高度*/\n"
"    padding:4px;/*内边距*/\n"
"}")
        self.refresh_models_button.setObjectName("refresh_models_button")
        self.browse_model_button = QtWidgets.QPushButton(Form)
        self.browse_model_button.setGeometry(QtCore.QRect(960, 500, 211, 40))
        self.browse_model_button.setMaximumSize(QtCore.QSize(16777215, 40))
        self.browse_model_button.setStyleSheet("QPushButton\n"
"{\n"
"    color:#ffffff; /*文字颜色*/\n"
"    background-color:qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop:0 #aa55ff, stop: 1 #1296db);/*背景色*/\n"
"    border-style:outset; /*边框风格*/\n"
"    border-width:2px;/*边框宽度*/\n"
"    border-color:#0055ff; /*边框颜色*/\n"
"    border-radius:10px; /*边框倒角*/\n"
"    font:bold 14px; /*字体*/\n"
"    font-family: Segoe UI;\n"
"    min-width:100px;/*控件最小宽度*/\n"
"    background-image: url(\"./image.png\");\n"
"    min-height:20px;/*控件最小高度*/\n"
"    padding:4px;/*内边距*/\n"
"}\n"
" \n"
"QPushButton:hover\n"
"{\n"
"    color:#ffffff; /*文字颜色*/\n"
"    background-color:qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop:0 #ff55ff, stop: 1 #1296db);/*背景色*/\n"
"    border-style:outset; /*边框风格*/\n"
"    border-width:2px;/*边框宽度*/\n"
"    border-color:#0055ff; /*边框颜色*/\n"
"    border-radius:10px; /*边框倒角*/\n"
"    font:bold 14px; /*字体*/\n"
"    font-family: Segoe UI;\n"
"    min-width:100px;/*控件最小宽度*/\n"
"    min-height:20px;/*控件最小高度*/\n"
"    padding:4px;/*内边距*/\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    color:#ffffff; /*文字颜色*/\n"
"    background-color:qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop:0 #ff55ff, stop: 1 #aa00ff);/*背景色*/\n"
"    border-style:outset; /*边框风格*/\n"
"    border-width:2px;/*边框宽度*/\n"
"    border-color:#0055ff; /*边框颜色*/\n"
"    border-radius:10px; /*边框倒角*/\n"
"    font:bold 14px; /*字体*/\n"
"    font-family: Segoe UI;\n"
"    min-width:100px;/*控件最小宽度*/\n"
"    min-height:20px;/*控件最小高度*/\n"
"    padding:4px;/*内边距*/\n"
"}")
        self.browse_model_button.setObjectName("browse_model_button")
        self.output_image_label_3 = QtWidgets.QLabel(Form)
        self.output_image_label_3.setGeometry(QtCore.QRect(1010, 590, 191, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(18)
        self.output_image_label_3.setFont(font)
        self.output_image_label_3.setObjectName("output_image_label_3")
        self.title = QtWidgets.QLabel(Form)
        self.title.setGeometry(QtCore.QRect(360, 10, 391, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(24)
        self.title.setFont(font)
        self.title.setObjectName("title")
        self.detected_image.raise_()
        self.original_image.raise_()
        self.layoutWidget.raise_()
        self.resultTable.raise_()
        self.result_label.raise_()
        self.input_image_label.raise_()
        self.output_image_label.raise_()
        self.save_result_pushButton.raise_()
        self.doubt_accuracy_pushButton.raise_()
        self.model_combobox.raise_()
        self.output_image_label_2.raise_()
        self.refresh_models_button.raise_()
        self.browse_model_button.raise_()
        self.output_image_label_3.raise_()
        self.title.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.original_image.setText(_translate("Form", "初始图片"))
        self.detected_image.setText(_translate("Form", "检测结果"))
        self.picture_detect_pushButton.setText(_translate("Form", "导入图片"))
        self.stop_detect_pushButton.setText(_translate("Form", "结束当前检测"))
        self.exit_system_pushButton.setText(_translate("Form", "退出系统"))
        self.result_label.setText(_translate("Form", "检测结果(类别/置信度/xywh)"))
        self.input_image_label.setText(_translate("Form", "输入图像"))
        self.output_image_label.setText(_translate("Form", "检测结果"))
        self.save_result_pushButton.setText(_translate("Form", "保存结果图片"))
        self.doubt_accuracy_pushButton.setText(_translate("Form", "质疑结果"))
        self.output_image_label_2.setText(_translate("Form", "选择模型"))
        self.refresh_models_button.setText(_translate("Form", "刷新模型列表"))
        self.browse_model_button.setText(_translate("Form", "浏览模型文件"))
        self.output_image_label_3.setText(_translate("Form", "version 1.0.0"))
        self.title.setText(_translate("Form", "草地虫害在线识别系统"))
